window.PORTFOLIO_DATA = {
  "places": [
    {
      "id": "haiyan",
      "name": "海晏村",
      "englishName": "Haiyan Village",
      "location": "云南 昆明",
      "coordinate": "24.816 N, 102.787 E",
      "coverImage": "./images/places/haiyan/cover.jpg",
      "mood": "湖边、老街、咖啡、木门、慢生活",
      "summary": "海晏村不是那种一上来就很吵的景点。它更像一个把节奏调慢的湖边小镇：有人坐着聊天，有人骑车穿过巷子，风把水面和旧墙都擦亮了一点。",
      "note": "这组照片适合慢慢看。黑白街巷、湖边背影、咖啡店招牌、老木门和桌上的饮料放在一起，像一次没有赶时间的下午散步。",
      "routeNote": "从滇池边开始，先把速度放下来。",
      "mapPosition": {
        "x": 41.5,
        "y": 74.3
      }
    },
    {
      "id": "laoyuhe",
      "name": "捞鱼河",
      "englishName": "Laoyuhe Wetland",
      "location": "云南 昆明",
      "coordinate": "24.758 N, 102.777 E",
      "coverImage": "./images/places/laoyuhe/cover.jpg",
      "mood": "湿地、渡船、水面、树影、倒影",
      "summary": "捞鱼河最有意思的是水面的脾气：船一来，画面就热闹；船一走，树影和倒影又把声音收回去。",
      "note": "这里的照片不靠大场面取胜，靠的是水面、树、船和光之间的小动作。很多画面像把真实世界翻了个面。",
      "routeNote": "这里适合等一等，等水面把答案倒过来。",
      "mapPosition": {
        "x": 46.5,
        "y": 69.0
      }
    },
    {
      "id": "dounan",
      "name": "斗南",
      "englishName": "Dounan Flower Market",
      "location": "云南 昆明",
      "coordinate": "24.894 N, 102.795 E",
      "coverImage": "./images/places/dounan/cover.jpg",
      "mood": "花市、颜色、批发、包装、热闹",
      "summary": "斗南像一个颜色开会的地方。花被成束摆好、打包、搬运、出售，热闹但不乱，每一束都像带着自己的任务。",
      "note": "这里最适合训练眼睛：粉色、黄色、白色、蓝色、人造花和鲜花挤在一起，画面不用很复杂也会很有能量。",
      "routeNote": "在斗南，颜色比人先开口。",
      "mapPosition": {
        "x": 49.4,
        "y": 62.2
      }
    },
    {
      "id": "cuihu",
      "name": "翠湖",
      "englishName": "Green Lake",
      "location": "云南 昆明",
      "coordinate": "25.045 N, 102.706 E",
      "coverImage": "./images/places/cuihu/cover.jpg",
      "mood": "猫、红墙、海鸥、古建、城市日常",
      "summary": "翠湖是昆明很会生活的一面。猫在晒太阳，海鸥在水面排队，红墙和屋檐负责把城市的日常变得更有戏。",
      "note": "这组照片里有不少轻松的小角色：猫、松鼠、海鸥、花和帽子。它们让翠湖不只是景点，而像一个每天都在更新的公共客厅。",
      "routeNote": "城市在这里变得柔软一点，也更好聊天。",
      "mapPosition": {
        "x": 54.8,
        "y": 61.2
      }
    },
    {
      "id": "kmust",
      "name": "昆明理工大学",
      "englishName": "Kunming University of Science and Technology",
      "location": "云南 昆明",
      "coordinate": "25.063 N, 102.746 E",
      "coverImage": "./images/places/kmust/cover.jpg",
      "mood": "校园、夜灯、花、红旗、青春",
      "summary": "昆工这组照片有白天的明亮，也有夜里的黑白。校园最有意思的地方是：它很普通，但总会在某个角落突然发光。",
      "note": "我把校园拍得不像纪念照，更像路过时的记录。灯、花、旗帜、楼和云都很日常，但放在一起就有了一个阶段的气味。",
      "routeNote": "校园是地图上最日常的一站，也最容易突然想起很多事。",
      "mapPosition": {
        "x": 61.2,
        "y": 48.8
      }
    },
    {
      "id": "wulongcun",
      "name": "乌龙村",
      "englishName": "Wulong Village",
      "location": "云南 昆明",
      "coordinate": "24.790 N, 102.790 E",
      "coverImage": "./images/places/wulongcun/cover.jpg",
      "mood": "湖风、落日、旧屋、瓦檐、船",
      "summary": "乌龙村有两种速度：湖面和落日很开阔，老屋、瓦檐和小船又把人拉回很具体的日子。",
      "note": "这组照片一半看水，一半看房子。前者负责把心放远，后者负责提醒你脚下还有路。",
      "routeNote": "这里像地图上突然慢下来的一个拐弯。",
      "mapPosition": {
        "x": 67.1,
        "y": 47.0
      }
    },
    {
      "id": "zhenping",
      "name": "镇平",
      "englishName": "Zhenping",
      "location": "河南 南阳",
      "coordinate": "33.033 N, 112.235 E",
      "coverImage": "./images/places/zhenping/cover.jpg",
      "mood": "归乡、孩子、街头、招牌、夜色",
      "summary": "镇平这一组更像私人相册：孩子的表情、墙上的电话、街边招牌、红色灯箱和水果摊，都不是大景，却很有生活的重量。",
      "note": "这组照片不负责证明哪里好看，它负责证明哪里熟悉。熟悉的地方一旦被认真看，也会有很多新东西冒出来。",
      "routeNote": "最后回到熟悉的地方，地图也变得没那么像地图。",
      "mapPosition": {
        "x": 72.7,
        "y": 39.0
      }
    },
    {
      "id": "shaolinsi",
      "name": "少林寺",
      "englishName": "Shaolin Temple",
      "location": "河南 登封",
      "coordinate": "34.507 N, 112.935 E",
      "coverImage": "./images/places/shaolinsi/cover.jpg",
      "mood": "古建、石刻、塔林、山门、木构",
      "summary": "少林寺的照片不需要太多解释，木头、石头、屋檐和塔林自己就很有分量。这里的光也比较硬，适合把结构拍清楚。",
      "note": "我更喜欢少林寺里那些不太喧闹的角落：石雕的表情、斗拱的颜色、门框里的远处、塔林投下来的影子。",
      "routeNote": "路线走到这里，画面开始变硬，时间感也更重。",
      "mapPosition": {
        "x": 75.8,
        "y": 30.8
      }
    }
  ],
  "photos": [
    {
      "id": "haiyan-01",
      "title": "店外的街边人群",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2025.12",
      "image": "./images/places/haiyan/haiyan-01.jpg",
      "alt": "海晏村 - 店外的街边人群",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“店外的街边人群”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-02",
      "title": "巷子里的电动车",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-02.jpg",
      "alt": "海晏村 - 巷子里的电动车",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“巷子里的电动车”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-03",
      "title": "巷子深处的行人",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-03.jpg",
      "alt": "海晏村 - 巷子深处的行人",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“巷子深处的行人”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-04",
      "title": "街巷里的骑车人",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-04.jpg",
      "alt": "海晏村 - 街巷里的骑车人",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“街巷里的骑车人”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-05",
      "title": "墙边聊天的人",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-05.jpg",
      "alt": "海晏村 - 墙边聊天的人",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“墙边聊天的人”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-06",
      "title": "墙边的婚纱与座位",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-06.jpg",
      "alt": "海晏村 - 墙边的婚纱与座位",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“墙边的婚纱与座位”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-07",
      "title": "海风站牌",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-07.jpg",
      "alt": "海晏村 - 海风站牌",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“海风站牌”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-08",
      "title": "室内楼梯的光",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026.03",
      "image": "./images/places/haiyan/haiyan-08.jpg",
      "alt": "海晏村 - 室内楼梯的光",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“室内楼梯的光”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-09",
      "title": "湖边的两个背影",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-09.jpg",
      "alt": "海晏村 - 湖边的两个背影",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“湖边的两个背影”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-10",
      "title": "湖边举手的人",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-10.jpg",
      "alt": "海晏村 - 湖边举手的人",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“湖边举手的人”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-11",
      "title": "水边玩耍的孩子",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-11.jpg",
      "alt": "海晏村 - 水边玩耍的孩子",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“水边玩耍的孩子”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-12",
      "title": "低头看地的小孩",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-12.jpg",
      "alt": "海晏村 - 低头看地的小孩",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“低头看地的小孩”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-13",
      "title": "伸向湖面的长堤",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-13.jpg",
      "alt": "海晏村 - 伸向湖面的长堤",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“伸向湖面的长堤”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-14",
      "title": "湖边墙下的人像",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-14.jpg",
      "alt": "海晏村 - 湖边墙下的人像",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“湖边墙下的人像”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-15",
      "title": "咖啡店里的红椅",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-15.jpg",
      "alt": "海晏村 - 咖啡店里的红椅",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“咖啡店里的红椅”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-16",
      "title": "小店门口的菜单",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-16.jpg",
      "alt": "海晏村 - 小店门口的菜单",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“小店门口的菜单”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-17",
      "title": "窗边的人像",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-17.jpg",
      "alt": "海晏村 - 窗边的人像",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“窗边的人像”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-18",
      "title": "光影下的侧脸",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-18.jpg",
      "alt": "海晏村 - 光影下的侧脸",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“光影下的侧脸”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-19",
      "title": "木格窗边的人像",
      "placeId": "haiyan",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-19.jpg",
      "alt": "海晏村 - 木格窗边的人像",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“木格窗边的人像”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-20",
      "title": "窗口里的收音机",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-20.jpg",
      "alt": "海晏村 - 窗口里的收音机",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“窗口里的收音机”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-21",
      "title": "云南生活的湖景牌",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-21.jpg",
      "alt": "海晏村 - 云南生活的湖景牌",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“云南生活的湖景牌”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-22",
      "title": "墙边桌椅和花瓶",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-22.jpg",
      "alt": "海晏村 - 墙边桌椅和花瓶",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“墙边桌椅和花瓶”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-23",
      "title": "木门上的海报",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-23.jpg",
      "alt": "海晏村 - 木门上的海报",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“木门上的海报”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-24",
      "title": "院门口的盆栽",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-24.jpg",
      "alt": "海晏村 - 院门口的盆栽",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“院门口的盆栽”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-25",
      "title": "沉茶店的门面",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-25.jpg",
      "alt": "海晏村 - 沉茶店的门面",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“沉茶店的门面”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-26",
      "title": "咖啡馆里的器物架",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-26.jpg",
      "alt": "海晏村 - 咖啡馆里的器物架",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“咖啡馆里的器物架”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-27",
      "title": "木门边的花纹",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-27.jpg",
      "alt": "海晏村 - 木门边的花纹",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“木门边的花纹”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-28",
      "title": "老窗格的暗光",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-28.jpg",
      "alt": "海晏村 - 老窗格的暗光",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“老窗格的暗光”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-29",
      "title": "木窗和门板",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-29.jpg",
      "alt": "海晏村 - 木窗和门板",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“木窗和门板”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-30",
      "title": "窗框里的树",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-30.jpg",
      "alt": "海晏村 - 窗框里的树",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“窗框里的树”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-31",
      "title": "馆院的墙面",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-31.jpg",
      "alt": "海晏村 - 馆院的墙面",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“馆院的墙面”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-32",
      "title": "蓝色纸花和小物",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-32.jpg",
      "alt": "海晏村 - 蓝色纸花和小物",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“蓝色纸花和小物”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-33",
      "title": "老院门的光",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-33.jpg",
      "alt": "海晏村 - 老院门的光",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“老院门的光”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-34",
      "title": "木门前的空位",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-34.jpg",
      "alt": "海晏村 - 木门前的空位",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“木门前的空位”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-35",
      "title": "饮品杯的桌面细节",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-35.jpg",
      "alt": "海晏村 - 饮品杯的桌面细节",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“饮品杯的桌面细节”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-36",
      "title": "窗边的饮品杯",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-36.jpg",
      "alt": "海晏村 - 窗边的饮品杯",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“窗边的饮品杯”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-37",
      "title": "桌上的饮品和纸张",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-37.jpg",
      "alt": "海晏村 - 桌上的饮品和纸张",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“桌上的饮品和纸张”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-38",
      "title": "饮品杯的俯拍",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-38.jpg",
      "alt": "海晏村 - 饮品杯的俯拍",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“饮品杯的俯拍”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-39",
      "title": "饮品杯和笔记本",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-39.jpg",
      "alt": "海晏村 - 饮品杯和笔记本",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“饮品杯和笔记本”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-40",
      "title": "湖边码头和海鸥",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-40.jpg",
      "alt": "海晏村 - 湖边码头和海鸥",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“湖边码头和海鸥”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-41",
      "title": "红顶塔楼",
      "placeId": "haiyan",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-41.jpg",
      "alt": "海晏村 - 红顶塔楼",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“红顶塔楼”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-42",
      "title": "柜台里的玩偶",
      "placeId": "haiyan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-42.jpg",
      "alt": "海晏村 - 柜台里的玩偶",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“柜台里的玩偶”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-43",
      "title": "树影落在水面",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-43.jpg",
      "alt": "海晏村 - 树影落在水面",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“树影落在水面”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-44",
      "title": "白花和绿叶",
      "placeId": "haiyan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-44.jpg",
      "alt": "海晏村 - 白花和绿叶",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“白花和绿叶”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-45",
      "title": "屋檐旁的绿植",
      "placeId": "haiyan",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-45.jpg",
      "alt": "海晏村 - 屋檐旁的绿植",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“屋檐旁的绿植”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-46",
      "title": "海风站和白伞",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-46.jpg",
      "alt": "海晏村 - 海风站和白伞",
      "orientation": "landscape",
      "description": "这张照片拍的是海晏村的“海风站和白伞”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "haiyan-47",
      "title": "湖边落日灯",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-47.jpg",
      "alt": "海晏村 - 湖边落日灯",
      "orientation": "square",
      "description": "这张照片拍的是海晏村的“湖边落日灯”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "haiyan-48",
      "title": "傍晚湖边的小灯",
      "placeId": "haiyan",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/haiyan/haiyan-48.jpg",
      "alt": "海晏村 - 傍晚湖边的小灯",
      "orientation": "square",
      "description": "这张照片拍的是海晏村的“傍晚湖边的小灯”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "laoyuhe-01",
      "title": "靠岸的渡船",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-01.jpg",
      "alt": "捞鱼河 - 靠岸的渡船",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“靠岸的渡船”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "laoyuhe-02",
      "title": "树影被水拉长",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-02.jpg",
      "alt": "捞鱼河 - 树影被水拉长",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“树影被水拉长”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "laoyuhe-03",
      "title": "暗红色的水边树",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-03.jpg",
      "alt": "捞鱼河 - 暗红色的水边树",
      "orientation": "square",
      "description": "这张照片拍的是捞鱼河的“暗红色的水边树”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "laoyuhe-04",
      "title": "水边店铺和人声",
      "placeId": "laoyuhe",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-04.jpg",
      "alt": "捞鱼河 - 水边店铺和人声",
      "orientation": "square",
      "description": "这张照片拍的是捞鱼河的“水边店铺和人声”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "laoyuhe-05",
      "title": "倒映的云和柳枝",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-05.jpg",
      "alt": "捞鱼河 - 倒映的云和柳枝",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“倒映的云和柳枝”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "laoyuhe-06",
      "title": "垂进水里的柳枝",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-06.jpg",
      "alt": "捞鱼河 - 垂进水里的柳枝",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“垂进水里的柳枝”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "laoyuhe-07",
      "title": "水面像一张旧纸",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-07.jpg",
      "alt": "捞鱼河 - 水面像一张旧纸",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“水面像一张旧纸”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "laoyuhe-08",
      "title": "绿影压住湖面",
      "placeId": "laoyuhe",
      "theme": "湿地",
      "date": "2026",
      "image": "./images/places/laoyuhe/laoyuhe-08.jpg",
      "alt": "捞鱼河 - 绿影压住湖面",
      "orientation": "landscape",
      "description": "这张照片拍的是捞鱼河的“绿影压住湖面”。画面主体是水、树影、船或倒影，描述围绕这些可见元素写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-01",
      "title": "秋千上的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-01.jpg",
      "alt": "翠湖 - 秋千上的猫",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“秋千上的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-02",
      "title": "台阶上的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-02.jpg",
      "alt": "翠湖 - 台阶上的猫",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“台阶上的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-03",
      "title": "躺着看镜头的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-03.jpg",
      "alt": "翠湖 - 躺着看镜头的猫",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“躺着看镜头的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-04",
      "title": "栏杆后的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-04.jpg",
      "alt": "翠湖 - 栏杆后的猫",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“栏杆后的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-05",
      "title": "古戏台正面",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-05.jpg",
      "alt": "翠湖 - 古戏台正面",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“古戏台正面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-06",
      "title": "圆洞里的楼阁",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-06.jpg",
      "alt": "翠湖 - 圆洞里的楼阁",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“圆洞里的楼阁”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-07",
      "title": "彩绘牌楼正面",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-07.jpg",
      "alt": "翠湖 - 彩绘牌楼正面",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“彩绘牌楼正面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-08",
      "title": "树枝上的松鼠",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-08.jpg",
      "alt": "翠湖 - 树枝上的松鼠",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“树枝上的松鼠”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-09",
      "title": "盯着镜头的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-09.jpg",
      "alt": "翠湖 - 盯着镜头的猫",
      "orientation": "square",
      "description": "这张照片拍的是翠湖的“盯着镜头的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "cuihu-10",
      "title": "栏杆后的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-10.jpg",
      "alt": "翠湖 - 栏杆后的猫",
      "orientation": "square",
      "description": "这张照片拍的是翠湖的“栏杆后的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "cuihu-11",
      "title": "抬头的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-11.jpg",
      "alt": "翠湖 - 抬头的猫",
      "orientation": "square",
      "description": "这张照片拍的是翠湖的“抬头的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "cuihu-12",
      "title": "玩偶旁的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-12.jpg",
      "alt": "翠湖 - 玩偶旁的猫",
      "orientation": "square",
      "description": "这张照片拍的是翠湖的“玩偶旁的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "cuihu-13",
      "title": "湖边的猫",
      "placeId": "cuihu",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-13.jpg",
      "alt": "翠湖 - 湖边的猫",
      "orientation": "square",
      "description": "这张照片拍的是翠湖的“湖边的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "cuihu-14",
      "title": "水面上的波光",
      "placeId": "cuihu",
      "theme": "湖岸",
      "date": "2025.12",
      "image": "./images/places/cuihu/cuihu-14.jpg",
      "alt": "翠湖 - 水面上的波光",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“水面上的波光”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-15",
      "title": "彩绘屋檐",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-15.jpg",
      "alt": "翠湖 - 彩绘屋檐",
      "orientation": "portrait",
      "description": "这张照片拍的是翠湖的“彩绘屋檐”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。竖幅让主体更靠近，适合看表情和细节。"
    },
    {
      "id": "cuihu-16",
      "title": "湖畔牌楼",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-16.jpg",
      "alt": "翠湖 - 湖畔牌楼",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“湖畔牌楼”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-17",
      "title": "红灯笼和湖心亭",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-17.jpg",
      "alt": "翠湖 - 红灯笼和湖心亭",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“红灯笼和湖心亭”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-18",
      "title": "屋檐下的阴影",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-18.jpg",
      "alt": "翠湖 - 屋檐下的阴影",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“屋檐下的阴影”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-19",
      "title": "白塔和秋树",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-19.jpg",
      "alt": "翠湖 - 白塔和秋树",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“白塔和秋树”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-20",
      "title": "金色屋檐",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-20.jpg",
      "alt": "翠湖 - 金色屋檐",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“金色屋檐”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-21",
      "title": "白楼与红花墙",
      "placeId": "cuihu",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-21.jpg",
      "alt": "翠湖 - 白楼与红花墙",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“白楼与红花墙”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-22",
      "title": "红花绕着白楼",
      "placeId": "cuihu",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-22.jpg",
      "alt": "翠湖 - 红花绕着白楼",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“红花绕着白楼”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-23",
      "title": "彩绘古建屋檐",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-23.jpg",
      "alt": "翠湖 - 彩绘古建屋檐",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“彩绘古建屋檐”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-24",
      "title": "湖面上的海鸥",
      "placeId": "cuihu",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-24.jpg",
      "alt": "翠湖 - 湖面上的海鸥",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“湖面上的海鸥”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-25",
      "title": "花丛里的石鸟",
      "placeId": "cuihu",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-25.jpg",
      "alt": "翠湖 - 花丛里的石鸟",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“花丛里的石鸟”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-26",
      "title": "花圈和草帽",
      "placeId": "cuihu",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-26.jpg",
      "alt": "翠湖 - 花圈和草帽",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“花圈和草帽”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-27",
      "title": "圆门里的院子",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-27.jpg",
      "alt": "翠湖 - 圆门里的院子",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“圆门里的院子”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "cuihu-28",
      "title": "枯枝后的亭子",
      "placeId": "cuihu",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/cuihu/cuihu-28.jpg",
      "alt": "翠湖 - 枯枝后的亭子",
      "orientation": "landscape",
      "description": "这张照片拍的是翠湖的“枯枝后的亭子”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-01",
      "title": "绿色包装里的花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-01.jpg",
      "alt": "斗南 - 绿色包装里的花束",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“绿色包装里的花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-02",
      "title": "粉玫瑰小方阵",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-02.jpg",
      "alt": "斗南 - 粉玫瑰小方阵",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉玫瑰小方阵”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-03",
      "title": "多肉花束",
      "placeId": "dounan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/dounan/dounan-03.jpg",
      "alt": "斗南 - 多肉花束",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“多肉花束”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-04",
      "title": "绿色玫瑰成排",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-04.jpg",
      "alt": "斗南 - 绿色玫瑰成排",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“绿色玫瑰成排”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-05",
      "title": "玫瑰花篮",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-05.jpg",
      "alt": "斗南 - 玫瑰花篮",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“玫瑰花篮”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-06",
      "title": "玫瑰花阵俯拍",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-06.jpg",
      "alt": "斗南 - 玫瑰花阵俯拍",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“玫瑰花阵俯拍”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-07",
      "title": "彩色珠子小物",
      "placeId": "dounan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/dounan/dounan-07.jpg",
      "alt": "斗南 - 彩色珠子小物",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“彩色珠子小物”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-08",
      "title": "蓝白小花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-08.jpg",
      "alt": "斗南 - 蓝白小花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“蓝白小花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-09",
      "title": "彩色纸花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-09.jpg",
      "alt": "斗南 - 彩色纸花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“彩色纸花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-10",
      "title": "手工挂件",
      "placeId": "dounan",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/dounan/dounan-10.jpg",
      "alt": "斗南 - 手工挂件",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“手工挂件”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-11",
      "title": "蓝白花桶",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-11.jpg",
      "alt": "斗南 - 蓝白花桶",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“蓝白花桶”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-12",
      "title": "蓝白菊花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-12.jpg",
      "alt": "斗南 - 蓝白菊花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“蓝白菊花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-13",
      "title": "花桶里的浅色花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-13.jpg",
      "alt": "斗南 - 花桶里的浅色花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“花桶里的浅色花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-14",
      "title": "蓝橙塑料花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-14.jpg",
      "alt": "斗南 - 蓝橙塑料花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“蓝橙塑料花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-15",
      "title": "向日葵花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-15.jpg",
      "alt": "斗南 - 向日葵花束",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“向日葵花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-16",
      "title": "粉色花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-16.jpg",
      "alt": "斗南 - 粉色花束",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉色花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-17",
      "title": "网套里的红玫瑰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-17.jpg",
      "alt": "斗南 - 网套里的红玫瑰",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“网套里的红玫瑰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-18",
      "title": "成排红玫瑰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-18.jpg",
      "alt": "斗南 - 成排红玫瑰",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“成排红玫瑰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-19",
      "title": "粉色绣球花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-19.jpg",
      "alt": "斗南 - 粉色绣球花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉色绣球花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-20",
      "title": "粉玫瑰花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-20.jpg",
      "alt": "斗南 - 粉玫瑰花束",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉玫瑰花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-21",
      "title": "粉白玫瑰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-21.jpg",
      "alt": "斗南 - 粉白玫瑰",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉白玫瑰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-22",
      "title": "白花里的红点",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-22.jpg",
      "alt": "斗南 - 白花里的红点",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“白花里的红点”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-23",
      "title": "白玫瑰和蓝色小花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-23.jpg",
      "alt": "斗南 - 白玫瑰和蓝色小花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“白玫瑰和蓝色小花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-24",
      "title": "粉白花篮",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-24.jpg",
      "alt": "斗南 - 粉白花篮",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉白花篮”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-25",
      "title": "向日葵和粉玫瑰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-25.jpg",
      "alt": "斗南 - 向日葵和粉玫瑰",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“向日葵和粉玫瑰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-26",
      "title": "彩色花墙",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-26.jpg",
      "alt": "斗南 - 彩色花墙",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“彩色花墙”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-27",
      "title": "冷色雏菊",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-27.jpg",
      "alt": "斗南 - 冷色雏菊",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“冷色雏菊”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-28",
      "title": "黄色菊花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-28.jpg",
      "alt": "斗南 - 黄色菊花",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“黄色菊花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-29",
      "title": "粉玫瑰花蕾",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-29.jpg",
      "alt": "斗南 - 粉玫瑰花蕾",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“粉玫瑰花蕾”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-30",
      "title": "白粉玫瑰花蕾",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-30.jpg",
      "alt": "斗南 - 白粉玫瑰花蕾",
      "orientation": "landscape",
      "description": "这张照片拍的是斗南的“白粉玫瑰花蕾”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "dounan-31",
      "title": "黄色小花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-31.jpg",
      "alt": "斗南 - 黄色小花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“黄色小花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-32",
      "title": "单支玫瑰花苞",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-32.jpg",
      "alt": "斗南 - 单支玫瑰花苞",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“单支玫瑰花苞”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-33",
      "title": "橙粉玫瑰花苞",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-33.jpg",
      "alt": "斗南 - 橙粉玫瑰花苞",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“橙粉玫瑰花苞”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-34",
      "title": "黑桶里的花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-34.jpg",
      "alt": "斗南 - 黑桶里的花束",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“黑桶里的花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-35",
      "title": "黑桶里的花束俯拍",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-35.jpg",
      "alt": "斗南 - 黑桶里的花束俯拍",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“黑桶里的花束俯拍”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-36",
      "title": "粉色小花一簇",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-36.jpg",
      "alt": "斗南 - 粉色小花一簇",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉色小花一簇”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-37",
      "title": "黑桶里的多肉花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-37.jpg",
      "alt": "斗南 - 黑桶里的多肉花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“黑桶里的多肉花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-38",
      "title": "绿叶多肉",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-38.jpg",
      "alt": "斗南 - 绿叶多肉",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“绿叶多肉”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-39",
      "title": "黑桶里的玫瑰卷",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-39.jpg",
      "alt": "斗南 - 黑桶里的玫瑰卷",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“黑桶里的玫瑰卷”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-40",
      "title": "绿叶特写",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-40.jpg",
      "alt": "斗南 - 绿叶特写",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“绿叶特写”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-41",
      "title": "粉花枝条",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-41.jpg",
      "alt": "斗南 - 粉花枝条",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉花枝条”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-42",
      "title": "紫红兰花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-42.jpg",
      "alt": "斗南 - 紫红兰花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫红兰花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-43",
      "title": "粉色兰花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-43.jpg",
      "alt": "斗南 - 粉色兰花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉色兰花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-44",
      "title": "逆光粉色兰花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-44.jpg",
      "alt": "斗南 - 逆光粉色兰花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“逆光粉色兰花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-45",
      "title": "白色兰花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-45.jpg",
      "alt": "斗南 - 白色兰花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“白色兰花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-46",
      "title": "白色花团",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-46.jpg",
      "alt": "斗南 - 白色花团",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“白色花团”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-47",
      "title": "紫色兰花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-47.jpg",
      "alt": "斗南 - 紫色兰花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫色兰花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-48",
      "title": "粉紫蝴蝶兰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-48.jpg",
      "alt": "斗南 - 粉紫蝴蝶兰",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉紫蝴蝶兰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-49",
      "title": "白色兰花侧面",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-49.jpg",
      "alt": "斗南 - 白色兰花侧面",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“白色兰花侧面”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-50",
      "title": "白绿花丛",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-50.jpg",
      "alt": "斗南 - 白绿花丛",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“白绿花丛”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-51",
      "title": "淡粉花苞",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-51.jpg",
      "alt": "斗南 - 淡粉花苞",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“淡粉花苞”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-52",
      "title": "紫红蝴蝶兰",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-52.jpg",
      "alt": "斗南 - 紫红蝴蝶兰",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫红蝴蝶兰”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-53",
      "title": "粉色玫瑰簇",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-53.jpg",
      "alt": "斗南 - 粉色玫瑰簇",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉色玫瑰簇”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-54",
      "title": "淡紫花枝",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-54.jpg",
      "alt": "斗南 - 淡紫花枝",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“淡紫花枝”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-55",
      "title": "彩色圆球菊",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-55.jpg",
      "alt": "斗南 - 彩色圆球菊",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“彩色圆球菊”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-56",
      "title": "粉黄小菊",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-56.jpg",
      "alt": "斗南 - 粉黄小菊",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“粉黄小菊”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-57",
      "title": "紫白花束",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-57.jpg",
      "alt": "斗南 - 紫白花束",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫白花束”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-58",
      "title": "绿白叶片",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-58.jpg",
      "alt": "斗南 - 绿白叶片",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“绿白叶片”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-59",
      "title": "紫色小星花",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-59.jpg",
      "alt": "斗南 - 紫色小星花",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫色小星花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "dounan-60",
      "title": "紫红蝴蝶兰一串",
      "placeId": "dounan",
      "theme": "花事",
      "date": "2026",
      "image": "./images/places/dounan/dounan-60.jpg",
      "alt": "斗南 - 紫红蝴蝶兰一串",
      "orientation": "square",
      "description": "这张照片拍的是斗南的“紫红蝴蝶兰一串”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "wulongcun-01",
      "title": "芦苇挡住的湖光",
      "placeId": "wulongcun",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-01.jpg",
      "alt": "乌龙村 - 芦苇挡住的湖光",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“芦苇挡住的湖光”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-02",
      "title": "太阳落在水面上",
      "placeId": "wulongcun",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-02.jpg",
      "alt": "乌龙村 - 太阳落在水面上",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“太阳落在水面上”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-03",
      "title": "红色落日和远山",
      "placeId": "wulongcun",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-03.jpg",
      "alt": "乌龙村 - 红色落日和远山",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“红色落日和远山”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-04",
      "title": "岸边的小船",
      "placeId": "wulongcun",
      "theme": "湖岸",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-04.jpg",
      "alt": "乌龙村 - 岸边的小船",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“岸边的小船”。重点放在水面、岸线或远处的光，画面和标题保持在同一个湖边场景里。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-05",
      "title": "门口的红灯笼",
      "placeId": "wulongcun",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-05.jpg",
      "alt": "乌龙村 - 门口的红灯笼",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“门口的红灯笼”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-06",
      "title": "窗里的植物",
      "placeId": "wulongcun",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-06.jpg",
      "alt": "乌龙村 - 窗里的植物",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“窗里的植物”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-07",
      "title": "窗后的灯笼",
      "placeId": "wulongcun",
      "theme": "村落",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-07.jpg",
      "alt": "乌龙村 - 窗后的灯笼",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“窗后的灯笼”。文字只描述街巷、门面、旧墙和村里的生活痕迹，不额外添加画面里没有的对象。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-08",
      "title": "木门正面",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-08.jpg",
      "alt": "乌龙村 - 木门正面",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“木门正面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-09",
      "title": "老木门和瓦檐",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-09.jpg",
      "alt": "乌龙村 - 老木门和瓦檐",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“老木门和瓦檐”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-10",
      "title": "瓦檐的弧线",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-10.jpg",
      "alt": "乌龙村 - 瓦檐的弧线",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“瓦檐的弧线”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-11",
      "title": "红绸和灯笼",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-11.jpg",
      "alt": "乌龙村 - 红绸和灯笼",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“红绸和灯笼”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-12",
      "title": "旧屋的侧面",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-12.jpg",
      "alt": "乌龙村 - 旧屋的侧面",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“旧屋的侧面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-13",
      "title": "村里的墙角",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-13.jpg",
      "alt": "乌龙村 - 村里的墙角",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“村里的墙角”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "wulongcun-14",
      "title": "老门楼的匾额",
      "placeId": "wulongcun",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/wulongcun/wulongcun-14.jpg",
      "alt": "乌龙村 - 老门楼的匾额",
      "orientation": "landscape",
      "description": "这张照片拍的是乌龙村的“老门楼的匾额”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-01",
      "title": "旧壁画上的红色",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-01.jpg",
      "alt": "少林寺 - 旧壁画上的红色",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“旧壁画上的红色”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-02",
      "title": "大雄宝殿匾额",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-02.jpg",
      "alt": "少林寺 - 大雄宝殿匾额",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“大雄宝殿匾额”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-03",
      "title": "石狮仰视",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-03.jpg",
      "alt": "少林寺 - 石狮仰视",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“石狮仰视”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-04",
      "title": "缝隙里的斗拱",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-04.jpg",
      "alt": "少林寺 - 缝隙里的斗拱",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“缝隙里的斗拱”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-05",
      "title": "彩色斗拱正面",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-05.jpg",
      "alt": "少林寺 - 彩色斗拱正面",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“彩色斗拱正面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-06",
      "title": "木构屋檐的中心",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-06.jpg",
      "alt": "少林寺 - 木构屋檐的中心",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“木构屋檐的中心”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-07",
      "title": "石兽侧面",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-07.jpg",
      "alt": "少林寺 - 石兽侧面",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“石兽侧面”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-08",
      "title": "木构屋顶的中心",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-08.jpg",
      "alt": "少林寺 - 木构屋顶的中心",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“木构屋顶的中心”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-09",
      "title": "屋檐下的彩绘",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-09.jpg",
      "alt": "少林寺 - 屋檐下的彩绘",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“屋檐下的彩绘”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-10",
      "title": "达摩石刻",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-10.jpg",
      "alt": "少林寺 - 达摩石刻",
      "orientation": "square",
      "description": "这张照片拍的是少林寺的“达摩石刻”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "shaolinsi-11",
      "title": "斗拱里的阴影",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-11.jpg",
      "alt": "少林寺 - 斗拱里的阴影",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“斗拱里的阴影”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-12",
      "title": "石栏柱头",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-12.jpg",
      "alt": "少林寺 - 石栏柱头",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“石栏柱头”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-13",
      "title": "门框里的游客",
      "placeId": "shaolinsi",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-13.jpg",
      "alt": "少林寺 - 门框里的游客",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“门框里的游客”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-14",
      "title": "屋檐下的石兽",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-14.jpg",
      "alt": "少林寺 - 屋檐下的石兽",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“屋檐下的石兽”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-15",
      "title": "塔林的细节",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-15.jpg",
      "alt": "少林寺 - 塔林的细节",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“塔林的细节”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-16",
      "title": "塔林里的小路",
      "placeId": "shaolinsi",
      "theme": "古建",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-16.jpg",
      "alt": "少林寺 - 塔林里的小路",
      "orientation": "square",
      "description": "这张照片拍的是少林寺的“塔林里的小路”。说明聚焦屋檐、斗拱、石刻、门楼或塔林等可见结构。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "shaolinsi-17",
      "title": "山间缆车",
      "placeId": "shaolinsi",
      "theme": "手记",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-17.jpg",
      "alt": "少林寺 - 山间缆车",
      "orientation": "square",
      "description": "这张照片拍的是少林寺的“山间缆车”。这张更像路上顺手记下的一页，说明保持轻一点，不硬拔高。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "shaolinsi-18",
      "title": "山门外的光",
      "placeId": "shaolinsi",
      "theme": "手记",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-18.jpg",
      "alt": "少林寺 - 山门外的光",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“山门外的光”。这张更像路上顺手记下的一页，说明保持轻一点，不硬拔高。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "shaolinsi-19",
      "title": "寺院里的猫",
      "placeId": "shaolinsi",
      "theme": "人间",
      "date": "2026",
      "image": "./images/places/shaolinsi/shaolinsi-19.jpg",
      "alt": "少林寺 - 寺院里的猫",
      "orientation": "landscape",
      "description": "这张照片拍的是少林寺的“寺院里的猫”。标题对应画面里的具体人或动物，说明也围绕这个主体展开。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-01",
      "title": "玻璃上的云影",
      "placeId": "kmust",
      "theme": "校园",
      "date": "2026",
      "image": "./images/places/kmust/kmust-01.jpg",
      "alt": "昆明理工大学 - 玻璃上的云影",
      "orientation": "portrait",
      "description": "这张照片拍的是昆明理工大学的“玻璃上的云影”。说明围绕校名、楼体、旗帜、云和校园环境。竖幅让主体更靠近，适合看表情和细节。"
    },
    {
      "id": "kmust-02",
      "title": "黑白校名",
      "placeId": "kmust",
      "theme": "夜色",
      "date": "2026.03",
      "image": "./images/places/kmust/kmust-02.jpg",
      "alt": "昆明理工大学 - 黑白校名",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“黑白校名”。说明只围绕夜里的灯、招牌或车灯，不把白天画面写成夜景。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-03",
      "title": "夜里的路灯",
      "placeId": "kmust",
      "theme": "夜色",
      "date": "2026.03",
      "image": "./images/places/kmust/kmust-03.jpg",
      "alt": "昆明理工大学 - 夜里的路灯",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“夜里的路灯”。说明只围绕夜里的灯、招牌或车灯，不把白天画面写成夜景。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-04",
      "title": "夜色里的车灯",
      "placeId": "kmust",
      "theme": "夜色",
      "date": "2026.03",
      "image": "./images/places/kmust/kmust-04.jpg",
      "alt": "昆明理工大学 - 夜色里的车灯",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“夜色里的车灯”。说明只围绕夜里的灯、招牌或车灯，不把白天画面写成夜景。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-05",
      "title": "黄色小花",
      "placeId": "kmust",
      "theme": "花事",
      "date": "2026.05",
      "image": "./images/places/kmust/kmust-05.jpg",
      "alt": "昆明理工大学 - 黄色小花",
      "orientation": "square",
      "description": "这张照片拍的是昆明理工大学的“黄色小花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "kmust-06",
      "title": "樱花和楼角",
      "placeId": "kmust",
      "theme": "花事",
      "date": "2024.92",
      "image": "./images/places/kmust/kmust-06.jpg",
      "alt": "昆明理工大学 - 樱花和楼角",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“樱花和楼角”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-07",
      "title": "一整枝粉色花",
      "placeId": "kmust",
      "theme": "花事",
      "date": "2024.98",
      "image": "./images/places/kmust/kmust-07.jpg",
      "alt": "昆明理工大学 - 一整枝粉色花",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“一整枝粉色花”。标题直接写花的颜色、形状或摆放方式，避免把一种花误写成另一种。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-08",
      "title": "红旗和蓝天",
      "placeId": "kmust",
      "theme": "校园",
      "date": "2026",
      "image": "./images/places/kmust/kmust-08.jpg",
      "alt": "昆明理工大学 - 红旗和蓝天",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“红旗和蓝天”。说明围绕校名、楼体、旗帜、云和校园环境。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-09",
      "title": "校门前的建筑",
      "placeId": "kmust",
      "theme": "校园",
      "date": "2026",
      "image": "./images/places/kmust/kmust-09.jpg",
      "alt": "昆明理工大学 - 校门前的建筑",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“校门前的建筑”。说明围绕校名、楼体、旗帜、云和校园环境。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-10",
      "title": "主楼和云",
      "placeId": "kmust",
      "theme": "校园",
      "date": "2026",
      "image": "./images/places/kmust/kmust-10.jpg",
      "alt": "昆明理工大学 - 主楼和云",
      "orientation": "landscape",
      "description": "这张照片拍的是昆明理工大学的“主楼和云”。说明围绕校名、楼体、旗帜、云和校园环境。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "kmust-11",
      "title": "橙色楼体侧面",
      "placeId": "kmust",
      "theme": "校园",
      "date": "2026",
      "image": "./images/places/kmust/kmust-11.jpg",
      "alt": "昆明理工大学 - 橙色楼体侧面",
      "orientation": "square",
      "description": "这张照片拍的是昆明理工大学的“橙色楼体侧面”。说明围绕校名、楼体、旗帜、云和校园环境。方形构图把边缘收紧，主体更集中。"
    },
    {
      "id": "zhenping-01",
      "title": "孩子睁大眼睛",
      "placeId": "zhenping",
      "theme": "归乡",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-01.jpg",
      "alt": "镇平 - 孩子睁大眼睛",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“孩子睁大眼睛”。说明围绕孩子、熟悉街头和回家场景，保持私人但不乱写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-02",
      "title": "孩子看向镜头",
      "placeId": "zhenping",
      "theme": "归乡",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-02.jpg",
      "alt": "镇平 - 孩子看向镜头",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“孩子看向镜头”。说明围绕孩子、熟悉街头和回家场景，保持私人但不乱写。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-03",
      "title": "墙上的旧电话",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-03.jpg",
      "alt": "镇平 - 墙上的旧电话",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“墙上的旧电话”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-04",
      "title": "街边招牌的一角",
      "placeId": "zhenping",
      "theme": "城市",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-04.jpg",
      "alt": "镇平 - 街边招牌的一角",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“街边招牌的一角”。文字对应街边、店面、建筑或公共空间里的可见细节。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-05",
      "title": "街边招牌和栅栏",
      "placeId": "zhenping",
      "theme": "城市",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-05.jpg",
      "alt": "镇平 - 街边招牌和栅栏",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“街边招牌和栅栏”。文字对应街边、店面、建筑或公共空间里的可见细节。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-06",
      "title": "挂起来的包",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-06.jpg",
      "alt": "镇平 - 挂起来的包",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“挂起来的包”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-07",
      "title": "捆好的纸包",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-07.jpg",
      "alt": "镇平 - 捆好的纸包",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“捆好的纸包”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-08",
      "title": "打开的书页",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-08.jpg",
      "alt": "镇平 - 打开的书页",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“打开的书页”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-09",
      "title": "车窗里的树影",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-09.jpg",
      "alt": "镇平 - 车窗里的树影",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“车窗里的树影”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-10",
      "title": "车顶上的玩偶",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-10.jpg",
      "alt": "镇平 - 车顶上的玩偶",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“车顶上的玩偶”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-11",
      "title": "草莓水果盒",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-11.jpg",
      "alt": "镇平 - 草莓水果盒",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“草莓水果盒”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-12",
      "title": "红色漫画头像",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-12.jpg",
      "alt": "镇平 - 红色漫画头像",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“红色漫画头像”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-13",
      "title": "肯德基头像",
      "placeId": "zhenping",
      "theme": "城市",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-13.jpg",
      "alt": "镇平 - 肯德基头像",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“肯德基头像”。文字对应街边、店面、建筑或公共空间里的可见细节。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-14",
      "title": "夜里的肯德基门店",
      "placeId": "zhenping",
      "theme": "夜色",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-14.jpg",
      "alt": "镇平 - 夜里的肯德基门店",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“夜里的肯德基门店”。说明只围绕夜里的灯、招牌或车灯，不把白天画面写成夜景。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-15",
      "title": "红色店面橱窗",
      "placeId": "zhenping",
      "theme": "夜色",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-15.jpg",
      "alt": "镇平 - 红色店面橱窗",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“红色店面橱窗”。说明只围绕夜里的灯、招牌或车灯，不把白天画面写成夜景。横幅把环境一起带进来，现场关系更清楚。"
    },
    {
      "id": "zhenping-16",
      "title": "水果串和小物",
      "placeId": "zhenping",
      "theme": "静物",
      "date": "2026",
      "image": "./images/places/zhenping/zhenping-16.jpg",
      "alt": "镇平 - 水果串和小物",
      "orientation": "landscape",
      "description": "这张照片拍的是镇平的“水果串和小物”。文字对应画面里的小物、饮品、书页、玩偶或器物。横幅把环境一起带进来，现场关系更清楚。"
    }
  ],
  "themes": [
    "湖岸",
    "村落",
    "人间",
    "手记",
    "湿地",
    "夜色",
    "城市",
    "花事",
    "古建",
    "静物",
    "校园",
    "归乡"
  ]
};
